### ISSUE TITLE
Fix Encryption

### ISSUE THREAD

**Issue by etkirsch** [neuravion/mesh-chat#13]
We should not be "using" PKCS1.15

**Comment by NullVoxPopuli** [comment]
What should wee be using?

**Comment by NullVoxPopuli** [comment]
isn't that just the padding technique? Rather than overall encryption?

**Comment by etkirsch** [comment]
It's just vulnerable. Go get your teeth out

**Comment by NullVoxPopuli** [comment]
I did. Rachel has stories.  Haha

**Comment by etkirsch** [comment]
user stories?

**Comment by NullVoxPopuli** [comment]
Any updates on this?

**Comment by NullVoxPopuli** [comment]
NaCl recommends

_Encryption_: XSalsa20 stream cipher
_Authentication_: Poly1305 MAC
_Public Keys_: Curve25519 high-speed elliptic curve cryptography
- https://github.com/cryptosphere/rbnacl/wiki/Public-Key-Encryption

Does this mean RSA is obsolete? idk yet.

I asked the NaCl guy about this: https://github.com/cryptosphere/rbnacl/issues/133

**Comment by etkirsch** [comment]
We need to find stuff that can be readily used in Go and python too

**Comment by NullVoxPopuli** [comment]
Python:
[XSalsa20](https://pypi.python.org/pypi/salsa20/0.3.0)
[Poly1305](https://github.com/Varbin/python-poly1305/tree/master)
[Curve25519](https://github.com/tgalal/python-axolotl-curve25519)

Go:
[XSalsa20](https://github.com/golang/crypto/tree/master/salsa20)
[Poly1305](https://godoc.org/golang.org/x/crypto/poly1305)
[Curve25519](https://godoc.org/golang.org/x/crypto/curve25519)
[Other Crypto Packages](https://github.com/golang/crypto)

Go has all the crypto built in. :-)  
The Python ones look very ad-doc :-\

**Comment by NullVoxPopuli** [comment]
According the the NaCl guy, AES is ok, RSA is bad.

But we should be using GCM instead of CBC for our block cipher. 
http://crypto.stackexchange.com/questions/2310/what-is-the-difference-between-cbc-and-gcm-mode

RSA
- The large keys make it slow, 
- require use of bignums, and therefore make it difficult to implement in constant time. 
- Poor padding modes like PKCS#1v1.5 have plagued RSA for years.

**Comment by NullVoxPopuli** [comment]
Usecase for NaCl or LibSodium: https://labs.opendns.com/2013/03/06/announcing-sodium-a-new-cryptographic-library/

https://forum.safenetwork.io/t/question-about-nacl-encryption/3374/2
- CPUs are not optimized for AES 512

This guy brought up something I hadn't thought about: http://security.stackexchange.com/questions/42698/encryption-which-are-arent-nsa-backdoored
That there may be secret back doors into some algorithms.. not sure how true that is or not. but I'm learning towords it being a little tin-foil-hat-y

**Comment by NullVoxPopuli** [comment]
explanation of how the new public key encryption works with NaCl, including a code example: https://github.com/cryptosphere/rbnacl/wiki/Public-Key-Encryption

**Comment by b264** [comment]
Multiple encryption layers/schemes? :-D  Cancel "holes" out like negative exponents

**Comment by b264** [comment]
To me, speed of decryption should be the last thing we worry about.  In fact, the longer it takes, the better in some ways...

**Comment by NullVoxPopuli** [comment]
Agreed, but it looks like NaCl gives us more security while _also_ being faster. It's just a side-benefit.

**Comment by NullVoxPopuli** [comment]
Closing, cause it looks like NaCl solves all our problems.
