### ISSUE TITLE
messages must be signed and encrypted

### ISSUE THREAD

**Issue by NullVoxPopuli** [neuravion/mesh-chat#2]
so that no one can impersonate each other's uids
- use something RSA based

**Comment by NullVoxPopuli** [comment]
a note about preventing man in the middle attacks: https://blog.cloudflare.com/introducing-strict-ssl-protecting-against-a-man-in-the-middle-attack-on-origin-traffic/

ssl uses the certificate authority to verify certificates.
this means that there would have to be a known list of verified certificate authorities. :-\

**Comment by NullVoxPopuli** [comment]
more detail on CAs http://alienryderflex.com/man_in_the_middle/

**Comment by etkirsch** [comment]
Is this ready to be closed? Or do we want more info?

**Comment by NullVoxPopuli** [comment]
not until it's implemented. :-)

**Comment by NullVoxPopuli** [comment]
done
