### ISSUE TITLE
Forward Secrecy

### ISSUE THREAD

**Issue by b264** [neuravion/mesh-chat#20]
I was wondering if it's possible for us to implement this or not

**Comment by NullVoxPopuli** [comment]
Relates to #13 

This just means that if `personA`'s key is compromised, future communication to `personA` is not also comprimised

**Comment by NullVoxPopuli** [comment]
Also, https://en.wikipedia.org/wiki/Forward_secrecy

**Comment by NullVoxPopuli** [comment]
NaCl solves this.
