### ISSUE TITLE
Should we be using the public key for the uid? / or, should we pass the public key along with messages?

### ISSUE THREAD

**Issue by NullVoxPopuli** [neuravion/mesh-chat#24]
or, should the identity information be sent along with the message, unencryptedly?

currently, the required message format is simply:

```
{ message: 'encrypted message' }
```

after after everyone catches up with there NaCl support:

```
{ message: 'encrypted message', uid: 'uid-number' }
```

The reason for the addition of the UID is because the NaCl algorithms require both the public key (of Bob) and the private key (of Alice), in order to decrypt (from Bob). So... if all the messages would require this, why not just use the public key in the message payload?

Notes
- The public key is 'public' anyway, no reason to keep it secret, (though, right now, the public key is network-only)
- by sending the public key along with your payload, once the message is decrypted, you'd be able to tell who sent it (via the uid in the sender hash). This allows for a person to refresh their keys if they feel that there private key has become compromised.
  - This makes me think impersonation attempts would be more likely, so we may need a way for a user to somehow have an additional signature on their message, or we keep the one public key per user thing going.

thoughts?

**Comment by NullVoxPopuli** [comment]
Sending the public key along with the message would also help minimize the barrier to entry.

Currently (both people import):
- Alice exports her identity (uid, public key, alias)
- Bob exports his identity (uid, public key, alias)
- they both import eachother's public keys, because prior to now, there is no other way to have gotten the public keys

Suggested (only new people need to be imported):
- Alice exports her identity (uid, public key, alias)
- Bob imports Alice's identity
- Bob sends a message to Alice (containing the public key in cleartext)
- Alice receives Bob's message, and is able to decrypt it and then import Bob's derived identity from the message
- Bob and Alice can now communicate freely.

This would also allow for people to automatically exchange keys if they are both connected to the Relay... which would be pretty great. I'm less in-love with the manual adding of people to the network recently.

Thoughts? @etkirsch @ecollis6

**Comment by etkirsch** [comment]
Let's hold off on this until we get everyone using NaCl. I think it warrants consideration but I don't think the various clients are quite ready for this next step. The last bullet point in your Notes really concerns me and I think increased impersonation is highly likely..

The way we're doing it now may be cumbersome but it is very secure. So I'd say this is an issue for next week or so.

**Comment by NullVoxPopuli** [comment]
Well, security through obscurity is just temporary, ya know? Currently, the public key, uid, and alias are all public information. So, if we throw the public key in the cleartext part of the message (which I think we should), the clients should be responsible for verifying that the public key matches the uid -- maybe not ideal? 

Note that a message encrypted for a particular public key can't be done without a matching private key, so I think this sort of verification would be necessary to prevent people from changing their public keys (the dangerous part).

Alternatively, we could just send the uid around, and look up the public key (as we do now) -- which means clients have 0 chance of updating their existing public key.
This means that (as we are today) in order to change your public key, you need a new uid. 

Side Question: what if someone tries to auth to the network with the same uid as someone else?

The idea for #25 kinda stemmed off of this.

**Comment by etkirsch** [comment]
So... I don't think we're on the same page here and it might help if we talk it out on a whiteboard. I'll document our discussion and post it as a reply here.

**Comment by NullVoxPopuli** [comment]
Yeah, I vomited too many thoughts, and am having issues organizing it all :-(

**Comment by NullVoxPopuli** [comment]
For clarification, because we _want_ to emulate WASTE like exclusivity, both public and private keys should be treated as private. Otherwise, this allows anyone to join the network. We could use this for simultaneous public and private networks.

**Comment by etkirsch** [comment]
^ Good insight
